name: Post Update
run-name: Reusable Build Site CI

on:
  schedule:
    # https://crontab.guru/#0_8_*_*_*
    - cron:  '0 8 * * *'
  push:
    branches:
      - posts
      - master # <-- just for test
  workflow_dispatch:

concurrency:
  # group: build-${{ github.event.push.number || github.event.pull_request.number || github.ref }}
  group: update-post-reusing-workflow-actions
  cancel-in-progress: true

jobs:
  check-reusable-ci:
    env:
      NODE_OPTIONS: '--max_old_space_size=8192' #8192 4096 --expose-gc
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      node_version: 18

    runs-on: ubuntu-latest

    name: check other ci is not running
    steps:
      - uses: actions/checkout@v3
        name: checkout root project
        with:
          ref: master
          repository: dimaslanjaka/source-posts
          submodules: recursive
          token: '${{ secrets.ACCESS_TOKEN }}'
      - uses: actions/cache@v3
        id: cache
        name: init cache
        with:
          path: |
            ./site/db.json
            ./site/public
            ./site/tmp
            ./site/source/_posts
            ./site/multisite/chimeraland/tmp
            **/dist
            **/.yarn
          key: ${{ runner.os }}-${{ env.node_version }}
          restore-keys: |
            ${{ runner.os }}-${{ env.node_version }}
            ${{ runner.os }}-
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          check-latest: true
      - run: npm i -g ts-node typescript hexo-cli
      - name: clean install
        run: |
          yarn cache clean --all
          rm yarn.lock
          touch yarn.lock
          YARN_CHECKSUM_BEHAVIOR=update yarn install
      - run: ts-node src/ci/check-other-ci.ts

  call-workflow:
    needs: [check-reusable-ci]
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max_old_space_size=8192' #8192 4096 --expose-gc
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Deploy Stage
        uses: actions/github-script@v5
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              'dimaslanjaka',
              'static-blog-generator-hexo',
              'workflows/build-site.yml',
              'master'
            });
