name: Post Update

on:
  push:
    branches:
      - posts
  workflow_dispatch:

concurrency:
  # group: build-${{ github.event.push.number || github.event.pull_request.number || github.ref }}
  group: update-post-reusing-workflow-actions
  cancel-in-progress: true

jobs:
  wait-check:
    strategy:
      fail-fast: true
      max-parallel: 6

    runs-on: ubuntu-latest

    name: check other ci
    steps:
      - name: Dispatch an action and get the run ID
        uses: codex-/return-dispatch@v1
        id: return_dispatch
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repo: static-blog-generator-hexo
          ref: master
          owner: dimaslanjaka
          workflow: build-site.yml

  reusing-workflow:
    needs: [wait-check]
    uses: dimaslanjaka/static-blog-generator-hexo/.github/workflows/build-site.yml@master
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
